version: '3'
services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_USER: arpit
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb

  nextcloud:
    image: nextcloud:latest
    restart: always
    depends_on:
      - dbos
    ports:
      - 8081:80
    volumes:
      - nextcloud_storage_new:/var/www/html

volumes:
   nextcloud_storage_new:
   mysql_storage_new:

